// src/firebase/seedMenu.js
// Run once to populate Firestore with sample menu items
// Usage: node seedMenu.js (with firebase-admin configured)

const menuItems = [
  {
    id: "1",
    name: "Spicy Dragon Ramen",
    description: "Rich tonkotsu broth, chashu pork, soft-boiled egg, nori, bamboo shoots",
    price: 249,
    category: "Mains",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80",
    rating: 4.8,
    prepTime: "20 min",
    isVeg: false,
    bestseller: true,
  },
  {
    id: "2",
    name: "Margherita Classica",
    description: "San Marzano tomatoes, fresh mozzarella, basil, extra virgin olive oil",
    price: 199,
    category: "Mains",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
    rating: 4.6,
    prepTime: "15 min",
    isVeg: true,
    bestseller: false,
  },
  {
    id: "3",
    name: "Truffle Smash Burger",
    description: "Double smash patty, truffle mayo, caramelized onions, aged cheddar, brioche bun",
    price: 299,
    category: "Mains",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
    rating: 4.9,
    prepTime: "18 min",
    isVeg: false,
    bestseller: true,
  },
  {
    id: "4",
    name: "Avocado Toast Supreme",
    description: "Sourdough, smashed avocado, cherry tomatoes, feta, chili flakes, poached egg",
    price: 179,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=400&q=80",
    rating: 4.5,
    prepTime: "10 min",
    isVeg: true,
    bestseller: false,
  },
  {
    id: "5",
    name: "Mango Sticky Rice",
    description: "Glutinous coconut milk rice, fresh Alphonso mango slices, sesame crunch",
    price: 149,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=400&q=80",
    rating: 4.7,
    prepTime: "5 min",
    isVeg: true,
    bestseller: false,
  },
  {
    id: "6",
    name: "Korean BBQ Bowl",
    description: "Gochujang marinated chicken, steamed rice, kimchi, cucumber, sesame oil",
    price: 269,
    category: "Mains",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&q=80",
    rating: 4.8,
    prepTime: "22 min",
    isVeg: false,
    bestseller: true,
  },
  {
    id: "7",
    name: "Lemon Cheesecake",
    description: "New York style, graham cracker crust, lemon curd swirl, whipped cream",
    price: 129,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&q=80",
    rating: 4.6,
    prepTime: "2 min",
    isVeg: true,
    bestseller: false,
  },
  {
    id: "8",
    name: "Garlic Butter Prawns",
    description: "Tiger prawns, garlic butter, white wine reduction, ciabatta, fresh parsley",
    price: 349,
    category: "Starters",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80",
    rating: 4.9,
    prepTime: "12 min",
    isVeg: false,
    bestseller: true,
  },
];

// To seed: import this array and use setDoc in your app initialization
export { menuItems };